// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTSuugLmbNzR9T6pTzWZIR33evC-90xqk',
    appId: '1:706926145253:web:4c3153804d05b0aefbee0c',
    messagingSenderId: '706926145253',
    projectId: 'daty-41675',
    authDomain: 'daty-41675.firebaseapp.com',
    storageBucket: 'daty-41675.firebasestorage.app',
    measurementId: 'G-7TVJKJQWDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl1f7Pf7YIVVoAVRLV-ls5R4FaQ2FnodU',
    appId: '1:706926145253:android:2bfc5735764b41b0fbee0c',
    messagingSenderId: '706926145253',
    projectId: 'daty-41675',
    storageBucket: 'daty-41675.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFtR0WTv7PbuRd3PB-4VDjlO28GQDKTO8',
    appId: '1:706926145253:ios:20e7ee361f63f92cfbee0c',
    messagingSenderId: '706926145253',
    projectId: 'daty-41675',
    storageBucket: 'daty-41675.firebasestorage.app',
    iosClientId: '706926145253-oqabcv1gtctbuntglotuavvs2397dfuf.apps.googleusercontent.com',
    iosBundleId: 'com.example.magicDates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFtR0WTv7PbuRd3PB-4VDjlO28GQDKTO8',
    appId: '1:706926145253:ios:20e7ee361f63f92cfbee0c',
    messagingSenderId: '706926145253',
    projectId: 'daty-41675',
    storageBucket: 'daty-41675.firebasestorage.app',
    iosClientId: '706926145253-oqabcv1gtctbuntglotuavvs2397dfuf.apps.googleusercontent.com',
    iosBundleId: 'com.example.magicDates',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTSuugLmbNzR9T6pTzWZIR33evC-90xqk',
    appId: '1:706926145253:web:d4fb0e3126e66418fbee0c',
    messagingSenderId: '706926145253',
    projectId: 'daty-41675',
    authDomain: 'daty-41675.firebaseapp.com',
    storageBucket: 'daty-41675.firebasestorage.app',
    measurementId: 'G-MJC2WYZCMZ',
  );
}
